# Generated by Django 4.2.7 on 2023-11-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_imgae',
            new_name='profile_image',
        ),
    ]
