# Generated by Django 4.2.7 on 2023-11-08 16:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default.png', null=True, upload_to=accounts.models.get_file_path),
        ),
    ]
