# Generated by Django 4.2.7 on 2023-11-08 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='수상 제목')),
                ('content', models.TextField(max_length=255, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('category', models.CharField(choices=[('best_movies', '올해의_영화'), ('best_dramas', '올해의_드라마'), ('best_books', '올해의_책'), ('best_music', '올해의_음악'), ('best_moments', '올해의_순간'), ('best_hobbies', '올해의_취미'), ('best_discoveries', '올해의_발견'), ('best_habits', '올해의_습관'), ('best_sadness', '올해의_우울'), ('best_thoughts', '올해의_생각'), ('best_failures', '올해의_실패'), ('best_regrets', '올해의_후회'), ('best_humor', '올해의_유머'), ('best_tears', '올해의_눈물'), ('best_spending', '올해의_소비'), ('best_emotions', '올해의_감동'), ('best_travels', '올해의_여행'), ('best_food', '올해의_음식'), ('best_gifts', '올해의_선물'), ('next_year_me', '내년의_나')], max_length=20, verbose_name='카테고리')),
                ('category_id', models.PositiveIntegerField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/%Y/%m/%d')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boards.post')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
