# Generated by Django 4.2.7 on 2023-11-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
    ]
