# Generated by Django 4.2.7 on 2023-11-09 04:42

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_postimage_image_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=boards.models.post_image_path),
        ),
    ]
