# Generated by Django 4.2.7 on 2023-11-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_post_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='user',
        ),
    ]
