# Generated by Django 4.2.7 on 2023-11-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_rename_writer_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='writer',
        ),
    ]
