# Generated by Django 4.2.7 on 2023-11-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_rename_user_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='boards.post'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='boards.post'),
        ),
    ]
