name: Django CI

on:
  push:
      branches: ["main"]
  pull_request_target:
      types: [labeled, closed]

jobs:
  CI:
    if: contains(github.event.pull_request.labels.*.name, 'safe')
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Create .env
        shell: bash
        run: /
          touch .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }} >> .env
          echo KAKAO_ADMIN_KEY=${{ secrets.KAKAO_ADMIN_KEY }} >> .env
          echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> .env
          echo JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }} >> .env
          
          cat .env
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v2

      - name: Push
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}
